from __future__ import annotations

import json
import zipfile
from pathlib import Path

from common_extract import RAW, ROOT, raw_files, sha256_file


def zip_listing(path: Path, limit: int = 500) -> dict:
    try:
        with zipfile.ZipFile(path) as archive:
            names = archive.namelist()
            return {
                "entryCount": len(names),
                "firstEntries": names[:limit],
                "truncated": len(names) > limit,
            }
    except zipfile.BadZipFile:
        return {"error": "Not a readable ZIP archive"}


def main() -> None:
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    records = []
    for path in raw_files():
        record = {
            "name": path.name,
            "size": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        if path.suffix.lower() == ".zip":
            record["zip"] = zip_listing(path)
        records.append(record)

    lines = [
        "# Raw Source Tree",
        "",
        "Generated by `scripts/inspect_raw_sources.py`.",
        "",
        "Raw source files are local inputs and should remain ignored unless explicitly safe to commit.",
        "",
    ]
    for record in records:
        lines.append(f"## {record['name']}")
        lines.append("")
        lines.append(f"- Size: `{record['size']}` bytes")
        lines.append(f"- SHA-256: `{record['sha256']}`")
        if "zip" in record:
            zip_info = record["zip"]
            lines.append(f"- ZIP entries: `{zip_info.get('entryCount', 0)}`")
            if zip_info.get("error"):
                lines.append(f"- ZIP warning: {zip_info['error']}")
            else:
                lines.append("")
                lines.append("```txt")
                lines.extend(zip_info["firstEntries"])
                if zip_info.get("truncated"):
                    lines.append("... truncated ...")
                lines.append("```")
        lines.append("")

    (docs / "RAW_SOURCE_TREE.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    (docs / "RAW_SOURCE_TREE.json").write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Inspected {len(records)} raw source file(s) in {RAW}")


if __name__ == "__main__":
    main()
